"""scanner/hypothesis.py — LLM-powered vulnerability hypothesis generation.

Generates structured vulnerability hypotheses from Phase 2 annotated paths
that the deterministic scanner cannot confirm or reject.

Input paths by label:
- HEURISTIC_SINK — "This looks dangerous but I don't know what vulnerability it is"
- EXPOSED_NO_SOURCE — "This endpoint takes user input but I don't trace it"
- UNCOVERED_SINK — "This sink is reachable but no rule covers it"
- CONDITIONAL_SANITIZED — "There's a sanitizer but it might be bypassable"

For each path, the generator:
1. Builds a CPG-sliced code context (only the relevant code, not the full file)
2. Routes to the appropriate model tier via :class:`ModelRouter`
3. Produces structured :class:`Hypothesis` objects via Anthropic tool_use

When a :class:`NudgeLoop` is provided via *nudge_loop*, each LLM call is
wrapped in a multi-turn loop that prevents premature termination (empty
hypotheses, text-only responses, low-confidence submissions).  The nudge
system is adapted from AutoCVE — see :mod:`hyqagent.scanner.nudge` and
``docs/AUTOCVE-RESEARCH.md`` for attribution.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import structlog

if TYPE_CHECKING:
    from hyqagent.cpg.query import CPGQuery, GraphPath
    from hyqagent.cpg.types import BlindSpot
    from hyqagent.core.protocols import LlmProvider
    from hyqagent.models.router import ModelRouter
    from hyqagent.scanner.nudge import NudgeLoop

logger = structlog.get_logger(__name__)


# ── Hypothesis dataclass ─────────────────────────────────────────────────────


@dataclass
class Hypothesis:
    """A structured vulnerability hypothesis generated by an LLM.

    This is the raw LLM output — not yet validated. Feed to
    :class:`Validator` for L1 and L2 verification.
    """

    id: str
    vuln_type: str  # e.g. "sql_injection", "xss", "idor"
    cwe_id: str  # e.g. "CWE-89"
    severity: str  # critical | high | medium | low
    confidence: float  # 0.0 — 1.0 (LLM self-assessment)
    title: str
    description: str
    source_location: str  # "file.py:42"
    sink_location: str  # "file.py:128"
    evidence: str  # quoted code snippet
    reasoning: str  # LLM's explanation
    remediation: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def stable_key(self) -> str:
        """Deterministic identity for cross-round deduplication.

        Based on source_location + sink_location + vuln_type —
        the same vulnerability found in different rounds will have
        the same stable_key regardless of random ``id``.
        """
        return f"{self.source_location}|{self.sink_location}|{self.vuln_type}"


# ── Structured output schema (passed to Anthropic tool_use) ───────────────────

HYPOTHESIS_SCHEMA: dict[str, Any] = {
    "name": "report_hypotheses",
    "description": "Report vulnerability hypotheses found in the code",
    "input_schema": {
        "type": "object",
        "properties": {
            "hypotheses": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "vuln_type": {
                            "type": "string",
                            "description": (
                                "Vulnerability type: sql_injection, xss, "
                                "command_injection, path_traversal, ssrf, "
                                "deserialization, open_redirect, "
                                "code_injection, auth_bypass, xxe, ssti, "
                                "crypto_weakness, idor, csrf, "
                                "business_logic, info_disclosure, "
                                "race_condition, or other CWE-mapped type"
                            ),
                        },
                        "cwe_id": {
                            "type": "string",
                            "description": "CWE identifier, e.g. CWE-89",
                        },
                        "title": {
                            "type": "string",
                            "description": "Brief title summarising the finding",
                        },
                        "description": {
                            "type": "string",
                            "description": (
                                "Detailed description of the vulnerability, "
                                "including the data flow from source to sink"
                            ),
                        },
                        "severity": {
                            "type": "string",
                            "enum": ["critical", "high", "medium", "low", "info"],
                        },
                        "confidence": {
                            "type": "number",
                            "minimum": 0.0,
                            "maximum": 1.0,
                            "description": "LLM self-assessed confidence",
                        },
                        "source_location": {
                            "type": "string",
                            "description": "Source file:line of the taint source",
                        },
                        "sink_location": {
                            "type": "string",
                            "description": "Sink file:line of the taint sink",
                        },
                        "reasoning": {
                            "type": "string",
                            "description": (
                                "Step-by-step reasoning: why this is (or isn't) "
                                "a real vulnerability"
                            ),
                        },
                        "remediation": {
                            "type": "string",
                            "description": "Suggested fix or mitigation",
                        },
                    },
                    "required": [
                        "vuln_type",
                        "cwe_id",
                        "title",
                        "description",
                        "severity",
                        "confidence",
                        "reasoning",
                    ],
                },
            },
        },
        "required": ["hypotheses"],
    },
}


# ── Prompt templates ──────────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are a white-box security auditor analysing code for web application vulnerabilities.

## Your Task
Analyse the provided code slice and identify any security vulnerabilities.
For each finding, provide a structured report.

## Rules
1. Only report vulnerabilities that have concrete code evidence in the provided slice.
2. Be specific: cite exact line numbers, variable names, and function calls.
3. Consider the full attack chain: source (user input) → data flow → sink (dangerous operation).
4. If you are unsure, set confidence < 0.5 and explain your uncertainty.
5. For each finding, suggest a concrete remediation.

## Vulnerability Categories to Consider
- sql_injection: User input concatenated into SQL queries
- xss: Unsanitised user data rendered in HTML/JS
- command_injection: User input in system/shell commands
- path_traversal: User-controlled file paths without validation
- ssrf: User-controlled URLs in HTTP/database/network requests
- deserialization: Untrusted data in pickle/yaml/JSON deserialization
- open_redirect: User-controlled redirect URLs
- code_injection: User input in eval/exec/Function
- auth_bypass: Missing or broken authentication/authorisation checks
- xxe: XML external entity processing enabled
- ssti: Server-side template injection (user input in template rendering)
- crypto_weakness: Weak hashing (MD5/SHA1), weak ciphers, hardcoded keys
- idor: Insecure Direct Object Reference (missing ownership checks)
- csrf: Missing CSRF protection on state-changing operations
- info_disclosure: Stack traces, debug info, sensitive data in responses
- business_logic: Flawed business logic (e.g. negative price, bypassing workflow)

Use the report_hypotheses tool to output your findings."""


def _code_slice_prompt(
    slice_text: str,
    language: str,
    label: str,
    extra_context: str = "",
) -> str:
    """Build the user prompt for hypothesis generation."""
    label_desc = {
        "heuristic_sink": (
            "The CPG engine flagged this as a potentially dangerous operation "
            "(heuristic match) but could not determine the exact vulnerability type."
        ),
        "exposed_no_source": (
            "This HTTP endpoint accepts user input but the CPG engine could not "
            "trace a complete data flow path to a dangerous sink. There may be "
            "vulnerabilities that the static analysis missed."
        ),
        "uncovered_sink": (
            "This sink is reachable from user input but no specific vulnerability "
            "rule covers this combination."
        ),
        "conditional_sanitized": (
            "A sanitizer was detected on this path, but it is conditional — it "
            "may not execute in all scenarios. Determine if the sanitizer can be bypassed."
        ),
    }
    desc = label_desc.get(label, f"Label: {label}")

    prompt_parts = [
        f"## Code Context ({language})",
        f"**Reason for analysis**: {desc}",
    ]
    if extra_context:
        prompt_parts.append(f"\n**Additional context**: {extra_context}")
    prompt_parts.append(f"\n### CPG Data-Flow Slice\n```{language}\n{slice_text}\n```")
    prompt_parts.append(
        "\nAnalyse the code above. Report ALL vulnerabilities you find "
        "using the report_hypotheses tool."
    )

    return "\n".join(prompt_parts)


# ── HypothesisGenerator ──────────────────────────────────────────────────────


class HypothesisGenerator:
    """Generate vulnerability hypotheses from CPG-annotated paths.

    Usage::

        gen = HypothesisGenerator(query, router, provider, language)
        hypotheses = await gen.generate(annotated_paths)
    """

    def __init__(
        self,
        query: CPGQuery,
        router: ModelRouter,
        cheap_provider: LlmProvider,
        mid_provider: LlmProvider,
        strong_provider: LlmProvider,
        language: str,
        nudge_loop: NudgeLoop | None = None,
    ) -> None:
        self._query = query
        self._router = router
        self._language = language
        self._providers = {
            "anthropic": mid_provider,  # mid == strong share provider
            "deepseek": cheap_provider,
        }
        # Override strong to use same provider as mid (just different model)
        self._cheap = cheap_provider
        self._mid = mid_provider
        self._strong = strong_provider
        self._nudge_loop = nudge_loop
        # Recall-mode optional dependencies (set by orchestrator)
        self._code_retriever: Any = None
        self._agent_loop: Any = None

    # ── Public API ──────────────────────────────────────────────────────

    async def generate(
        self,
        annotated_paths: list[Any],  # AnnotatedPath
    ) -> list[Hypothesis]:
        """Generate hypotheses for a batch of annotated paths.

        Only processes labels that need LLM analysis:
        HEURISTIC_SINK, EXPOSED_NO_SOURCE, UNCOVERED_SINK.
        """
        hypotheses: list[Hypothesis] = []

        for ap in annotated_paths:
            label = getattr(ap, "label", None)
            if label is None:
                continue

            label_str = label.value if hasattr(label, "value") else str(label)

            generated = await self._generate_one(ap, label_str)
            hypotheses.extend(generated)

        logger.info(
            "hypothesis_generation_complete",
            total_hypotheses=len(hypotheses),
            input_paths=len(annotated_paths),
        )
        return hypotheses

    async def blind_scan(
        self,
        blind_spots: list[BlindSpot],
        file_snippets: dict[str, str],
    ) -> list[Hypothesis]:
        """Generate hypotheses for coverage blind spots.

        Each blind spot is paired with relevant file snippets for context.
        """
        if not blind_spots:
            return []

        # Build prompt from blind spots
        bs_text = "\n".join(
            f"- [{bs.severity}] {bs.location}: {bs.reason}\n  Recommendation: {bs.recommendation}"
            for bs in blind_spots[:20]  # limit prompt size
        )

        snippets_text = ""
        for fname, code in list(file_snippets.items())[:5]:
            snippets_text += f"\n### {fname}\n```{self._language}\n{code[:2000]}\n```\n"

        user_prompt = (
            f"## Coverage Blind Spots\n{bs_text}\n\n"
            f"## Relevant Code Files\n{snippets_text}\n\n"
            "Analyse the code for vulnerabilities matching the blind spot "
            "categories above. Use the report_hypotheses tool."
        )

        try:
            result = await self._cheap.generate_structured(
                messages=[{"role": "user", "content": user_prompt}],
                model=self._router.CHEAP_SPEC.model_id,
                output_schema=HYPOTHESIS_SCHEMA,
                system=SYSTEM_PROMPT,
                max_tokens=4096,
                temperature=0.1,
            )
            return self._parse_response(result)
        except Exception:
            logger.exception("blind_scan_failed")
            return []

    async def generate_from_seeds(
        self,
        seed_functions: list[str],
        sink_discoveries: list[dict[str, Any]] | None = None,
    ) -> list[Hypothesis]:
        """Generate hypotheses from saturation / reverse-sink seed functions.

        These functions were discovered as callers/callees of confirmed
        vulnerable sinks (saturation) or as sinks connected to unrecognised
        sources (reverse sink analysis).  The LLM investigates each one for
        vulnerabilities that the forward taint analysis may have missed.

        Args:
            seed_functions: Function names from :class:`SaturationScanner`.
            sink_discoveries: Reverse-sink discovery dicts (each with keys
                ``sink_name``, ``sink_file``, ``sink_line``,
                ``source_names``, ``taint_category``, ``confidence``).

        Returns:
            Generated hypotheses, empty list on failure.

        """
        if not seed_functions and not sink_discoveries:
            return []

        graph = getattr(self._query, "_graph", None)
        parts: list[str] = []

        # ── Seed functions from saturation ──────────────────────────────
        if seed_functions and graph is not None:
            parts.append("## Saturation Seeds (callers/callees of confirmed vulns)\n")
            parts.append(
                "These functions were discovered by expanding from confirmed "
                "vulnerable sinks along the CPG call graph.  They are adjacent "
                "to confirmed vulnerabilities and may share similar flaws.\n"
            )
            for seed_name in seed_functions:
                code = self._read_function_source(seed_name, graph)
                if code:
                    parts.append(code)
                else:
                    parts.append(f"- **{seed_name}** (source not available)")

        # ── Reverse-sink discoveries ────────────────────────────────────
        if sink_discoveries:
            parts.append("\n## Reverse Sink Discoveries (sinks → unrecognised sources)\n")
            parts.append(
                "These sinks were found by tracing backwards from function calls.  "
                "They reach user-input-like sources that the forward taint rules "
                "did NOT recognise — potential rule gaps.\n"
            )
            for disc in sink_discoveries[:15]:
                sn = disc.get("sink_name", "?")
                sf = disc.get("sink_file", "")
                sl = disc.get("sink_line", 0)
                srcs = ", ".join(disc.get("source_names", []) or [])
                tc = disc.get("taint_category", "")
                conf = disc.get("confidence", "medium")
                label = f" (labelled: {tc})" if tc else " (UNLABELLED)"
                parts.append(
                    f"- **{sn}** at `{sf}:{sl}`{label} — "
                    f"upstream sources: {srcs or 'none found'} "
                    f"[confidence: {conf}]"
                )

        if not parts:
            return []

        parts.append("\n## Task")
        parts.append(
            "Investigate the functions above for vulnerabilities.  Pay special "
            "attention to:\n"
            "1. Functions adjacent to known sinks — do they pass unsanitised data?\n"
            "2. Unlabelled sinks with user-input sources — are they dangerous?\n"
            "3. Each function's parameter flow — does user data reach a sink?\n"
        )

        user_prompt = "\n".join(parts)

        try:
            result = await self._cheap.generate_structured(
                messages=[{"role": "user", "content": user_prompt}],
                model=self._router.CHEAP_SPEC.model_id,
                output_schema=HYPOTHESIS_SCHEMA,
                system=SYSTEM_PROMPT,
                max_tokens=4096,
                temperature=0.2,
            )
            hyps = self._parse_response(result)
            logger.info(
                "generate_from_seeds_complete",
                seed_count=len(seed_functions),
                discovery_count=len(sink_discoveries or []),
                hypotheses=len(hyps),
            )
            return hyps
        except Exception:
            logger.exception("generate_from_seeds_failed")
            return []

    # ── Internal ────────────────────────────────────────────────────────

    def _read_function_source(self, func_name: str, graph: Any) -> str | None:
        """Read the source code of a function from the CPG graph.

        Returns a markdown code block, or ``None`` if not found.
        """
        for _nid, data in graph.nodes(data=True):
            if data.get("node_type") == "function" and data.get("name") == func_name:
                source = data.get("source", "")
                file_path = data.get("file_path", "")
                if source:
                    return (
                        f"### {func_name} ({file_path})\n"
                        f"```{self._language}\n{source[:1500]}\n```\n"
                    )
        return None

    async def _generate_one(
        self,
        annotated: Any,
        label_str: str,
    ) -> list[Hypothesis]:
        """Generate hypotheses for a single annotated path."""
        from hyqagent.models.router import Task, TaskType

        path = getattr(annotated, "path", None)
        if path is None:
            return []

        # 1. Build CPG slice
        slice_text = self._query.slice_path(path, context_lines=3)

        # 2. Assess complexity and route
        path_len = len(path.nodes) if path.nodes else 0
        cross_file = self._count_files(path)

        complexity = self._router.assess_complexity(
            path_length=path_len,
            cross_file_count=cross_file,
        )
        task = Task(
            task_type=TaskType.HYPOTHESIS_GENERATION,
            complexity=complexity,
            estimated_prompt_tokens=len(slice_text) // 3,
            metadata={"label": label_str},
        )
        provider, model_id = self._router.route(task)

        # 3. Build prompt
        extra = ""
        metadata = getattr(annotated, "metadata", {}) or {}
        if label_str == "heuristic_sink":
            score = metadata.get("score", 0)
            keywords = metadata.get("keywords", [])
            extra = f"Heuristic score: {score}/100. Matched keywords: {', '.join(keywords)}"
        elif label_str == "exposed_no_source":
            ep = metadata.get("endpoint", "")
            extra = f"Endpoint: {ep}"

        user_prompt = _code_slice_prompt(
            slice_text,
            self._language,
            label_str,
            extra,
        )

        # 4. Call LLM (with nudge protection if configured)
        try:
            # ── Recall mode: agentic exploration ──────────────────────
            if self._agent_loop is not None and self._code_retriever is not None:
                enriched = self._build_recall_prompt(annotated, label_str, slice_text, path)
                loop_result = await self._agent_loop.run(
                    messages=[{"role": "user", "content": enriched}],
                    output_schema=HYPOTHESIS_SCHEMA,
                    system=SYSTEM_PROMPT,
                    model=model_id,
                    max_tokens=4096,
                    temperature=0.2,
                )
                if loop_result is not None and loop_result.output:
                    return self._parse_response(loop_result.output)
                logger.warning(
                    "agent_loop_no_result",
                    label=label_str,
                    turns=loop_result.turns if loop_result else 0,
                )
                return []

            # ── Precision mode: single-shot ──────────────────────────
            if self._nudge_loop is not None:
                from hyqagent.scanner.nudge import stop_on_empty, stop_on_low_confidence

                nudge_result = await self._nudge_loop.run(
                    provider=provider,
                    model=model_id,
                    messages=[{"role": "user", "content": user_prompt}],
                    output_schema=HYPOTHESIS_SCHEMA,
                    system=SYSTEM_PROMPT,
                    max_tokens=4096,
                    temperature=0.1,
                    stop_hooks=[stop_on_empty("hypotheses"), stop_on_low_confidence(0.3)],
                )
                if nudge_result.success:
                    return self._parse_response(nudge_result.data)
                logger.warning(
                    "nudge_loop_incomplete",
                    label=label_str,
                    reason=nudge_result.termination_reason,
                    turns=nudge_result.turns,
                )
                return []
            else:
                result = await provider.generate_structured(
                    messages=[{"role": "user", "content": user_prompt}],
                    model=model_id,
                    output_schema=HYPOTHESIS_SCHEMA,
                    system=SYSTEM_PROMPT,
                    max_tokens=4096,
                    temperature=0.1,
                )
                return self._parse_response(result)
        except Exception:
            logger.exception(
                "hypothesis_generation_failed",
                label=label_str,
                model=model_id,
            )
            return []

    def _parse_response(self, raw: dict[str, Any]) -> list[Hypothesis]:
        """Parse structured LLM response into Hypothesis objects."""
        items = raw.get("hypotheses", [])
        if not isinstance(items, list):
            return []

        hypotheses: list[Hypothesis] = []
        for item in items:
            if not isinstance(item, dict):
                continue
            hypotheses.append(
                Hypothesis(
                    id=f"hyp-{uuid.uuid4().hex[:8]}",
                    vuln_type=item.get("vuln_type", "unknown"),
                    cwe_id=item.get("cwe_id", ""),
                    severity=item.get("severity", "medium"),
                    confidence=float(item.get("confidence", 0.5)),
                    title=item.get("title", "Untitled"),
                    description=item.get("description", ""),
                    source_location=item.get("source_location", ""),
                    sink_location=item.get("sink_location", ""),
                    evidence="",
                    reasoning=item.get("reasoning", ""),
                    remediation=item.get("remediation", ""),
                )
            )
        return hypotheses

    # ── Recall mode helpers ────────────────────────────────────────────

    def set_recall_deps(
        self,
        code_retriever: Any,
        agent_loop: Any,
    ) -> None:
        """Wire recall-mode dependencies (called by orchestrator)."""
        self._code_retriever = code_retriever
        self._agent_loop = agent_loop

    def _build_recall_prompt(
        self,
        annotated: Any,
        label_str: str,
        slice_text: str,
        path: Any,
    ) -> str:
        """Build an enriched prompt for recall-mode agentic exploration.

        Includes the CPG slice as a map plus the full sink function source
        from CodeRetriever so the LLM has both the trail and the terrain.
        """
        parts: list[str] = [
            "## Code Audit Task\n",
            f"**Label**: {label_str}",
        ]

        # CPG data-flow slice (the "trail")
        if slice_text:
            lang = self._language or ""
            parts.append(
                f"\n### CPG Data-Flow Slice (pre-computed path)\n```{lang}\n{slice_text}\n```"
            )

        # Full sink function source from CodeRetriever (the "terrain")
        if self._code_retriever is not None and path is not None:
            sink_node = None
            for node in path.nodes:
                ntype = getattr(node, "node_type", "")
                if ntype in ("call_site", "sink", "function_call"):
                    sink_node = node
                    break

            if sink_node is not None:
                loc = getattr(sink_node, "location", "")
                func_name = getattr(sink_node, "name", "")
                file_path = ""
                if ":" in loc:
                    file_path = loc.rsplit(":", 1)[0]

                if file_path and func_name:
                    chunks = self._code_retriever.get_chunks_for_file(file_path)
                    for chunk in chunks:
                        if chunk.function_name == func_name:
                            parts.append(
                                f"\n### Full Sink Function: {func_name}\n"
                                f"```\n{chunk.code[:2000]}\n```"
                            )
                            break

        # Tool guidance
        parts.append(
            "\n## Instructions\n"
            "You have code-exploration tools available (read_file, grep_code, "
            "get_function, list_functions, get_related). Use them to:\n"
            "1. Verify the data-flow path shown above\n"
            "2. Check for sanitizers or guards the scanner may have missed\n"
            "3. Look for related sink functions in the same file\n"
            "4. Determine if the vulnerability is exploitable in context\n\n"
            "When done, call the output tool with your hypotheses."
        )

        # Metadata
        metadata = getattr(annotated, "metadata", {}) or {}
        if label_str == "heuristic_sink":
            score = metadata.get("score", 0)
            keywords = metadata.get("keywords", [])
            parts.append(
                f"\n**Heuristic score**: {score}/100. **Matched keywords**: {', '.join(keywords)}"
            )

        return "\n".join(parts)

    @staticmethod
    def _count_files(path: GraphPath) -> int:
        """Count unique files across path nodes."""
        files: set[str] = set()
        for node in path.nodes:
            loc = getattr(node, "location", "")
            if ":" in loc:
                files.add(loc.rsplit(":", 1)[0])
        return len(files)
