"""scanner/hypothesis.py — LLM-powered vulnerability hypothesis generation.

Generates structured vulnerability hypotheses from Phase 2 annotated paths
that the deterministic scanner cannot confirm or reject.

Input paths by label:
- HEURISTIC_SINK — "This looks dangerous but I don't know what vulnerability it is"
- EXPOSED_NO_SOURCE — "This endpoint takes user input but I don't trace it"
- UNCOVERED_SINK — "This sink is reachable but no rule covers it"
- CONDITIONAL_SANITIZED — "There's a sanitizer but it might be bypassable"

For each path, the generator:
1. Builds a CPG-sliced code context (only the relevant code, not the full file)
2. Routes to the appropriate model tier via :class:`ModelRouter`
3. Produces structured :class:`Hypothesis` objects via Anthropic tool_use

When a :class:`NudgeLoop` is provided via *nudge_loop*, each LLM call is
wrapped in a multi-turn loop that prevents premature termination (empty
hypotheses, text-only responses, low-confidence submissions).  The nudge
system is adapted from AutoCVE — see :mod:`hyqagent.scanner.nudge` and
``docs/AUTOCVE-RESEARCH.md`` for attribution.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import structlog

if TYPE_CHECKING:
    from hyqagent.cpg.query import CPGQuery, GraphPath
    from hyqagent.cpg.types import BlindSpot
    from hyqagent.models.providers.anthropic_provider import AnthropicProvider
    from hyqagent.models.router import ModelRouter, Task, TaskType
    from hyqagent.scanner.nudge import NudgeLoop

logger = structlog.get_logger(__name__)


# ── Hypothesis dataclass ─────────────────────────────────────────────────────


@dataclass
class Hypothesis:
    """A structured vulnerability hypothesis generated by an LLM.

    This is the raw LLM output — not yet validated. Feed to
    :class:`Validator` for L1 and L2 verification.
    """

    id: str
    vuln_type: str  # e.g. "sql_injection", "xss", "idor"
    cwe_id: str  # e.g. "CWE-89"
    severity: str  # critical | high | medium | low
    confidence: float  # 0.0 — 1.0 (LLM self-assessment)
    title: str
    description: str
    source_location: str  # "file.py:42"
    sink_location: str  # "file.py:128"
    evidence: str  # quoted code snippet
    reasoning: str  # LLM's explanation
    remediation: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


# ── Structured output schema (passed to Anthropic tool_use) ───────────────────

HYPOTHESIS_SCHEMA: dict[str, Any] = {
    "name": "report_hypotheses",
    "description": "Report vulnerability hypotheses found in the code",
    "input_schema": {
        "type": "object",
        "properties": {
            "hypotheses": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "vuln_type": {
                            "type": "string",
                            "description": (
                                "Vulnerability type: sql_injection, xss, "
                                "command_injection, path_traversal, ssrf, "
                                "deserialization, open_redirect, "
                                "code_injection, auth_bypass, xxe, ssti, "
                                "crypto_weakness, idor, csrf, "
                                "business_logic, info_disclosure, "
                                "race_condition, or other CWE-mapped type"
                            ),
                        },
                        "cwe_id": {
                            "type": "string",
                            "description": "CWE identifier, e.g. CWE-89",
                        },
                        "title": {
                            "type": "string",
                            "description": "Brief title summarising the finding",
                        },
                        "description": {
                            "type": "string",
                            "description": (
                                "Detailed description of the vulnerability, "
                                "including the data flow from source to sink"
                            ),
                        },
                        "severity": {
                            "type": "string",
                            "enum": ["critical", "high", "medium", "low", "info"],
                        },
                        "confidence": {
                            "type": "number",
                            "minimum": 0.0,
                            "maximum": 1.0,
                            "description": "LLM self-assessed confidence",
                        },
                        "source_location": {
                            "type": "string",
                            "description": "Source file:line of the taint source",
                        },
                        "sink_location": {
                            "type": "string",
                            "description": "Sink file:line of the taint sink",
                        },
                        "reasoning": {
                            "type": "string",
                            "description": (
                                "Step-by-step reasoning: why this is (or isn't) "
                                "a real vulnerability"
                            ),
                        },
                        "remediation": {
                            "type": "string",
                            "description": "Suggested fix or mitigation",
                        },
                    },
                    "required": [
                        "vuln_type",
                        "cwe_id",
                        "title",
                        "description",
                        "severity",
                        "confidence",
                        "reasoning",
                    ],
                },
            },
        },
        "required": ["hypotheses"],
    },
}


# ── Prompt templates ──────────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are a white-box security auditor analysing code for web application vulnerabilities.

## Your Task
Analyse the provided code slice and identify any security vulnerabilities.
For each finding, provide a structured report.

## Rules
1. Only report vulnerabilities that have concrete code evidence in the provided slice.
2. Be specific: cite exact line numbers, variable names, and function calls.
3. Consider the full attack chain: source (user input) → data flow → sink (dangerous operation).
4. If you are unsure, set confidence < 0.5 and explain your uncertainty.
5. For each finding, suggest a concrete remediation.

## Vulnerability Categories to Consider
- sql_injection: User input concatenated into SQL queries
- xss: Unsanitised user data rendered in HTML/JS
- command_injection: User input in system/shell commands
- path_traversal: User-controlled file paths without validation
- ssrf: User-controlled URLs in HTTP/database/network requests
- deserialization: Untrusted data in pickle/yaml/JSON deserialization
- open_redirect: User-controlled redirect URLs
- code_injection: User input in eval/exec/Function
- auth_bypass: Missing or broken authentication/authorisation checks
- xxe: XML external entity processing enabled
- ssti: Server-side template injection (user input in template rendering)
- crypto_weakness: Weak hashing (MD5/SHA1), weak ciphers, hardcoded keys
- idor: Insecure Direct Object Reference (missing ownership checks)
- csrf: Missing CSRF protection on state-changing operations
- info_disclosure: Stack traces, debug info, sensitive data in responses
- business_logic: Flawed business logic (e.g. negative price, bypassing workflow)

Use the report_hypotheses tool to output your findings."""


def _code_slice_prompt(
    slice_text: str,
    language: str,
    label: str,
    extra_context: str = "",
) -> str:
    """Build the user prompt for hypothesis generation."""
    label_desc = {
        "heuristic_sink": (
            "The CPG engine flagged this as a potentially dangerous operation "
            "(heuristic match) but could not determine the exact vulnerability type."
        ),
        "exposed_no_source": (
            "This HTTP endpoint accepts user input but the CPG engine could not "
            "trace a complete data flow path to a dangerous sink. There may be "
            "vulnerabilities that the static analysis missed."
        ),
        "uncovered_sink": (
            "This sink is reachable from user input but no specific vulnerability "
            "rule covers this combination."
        ),
        "conditional_sanitized": (
            "A sanitizer was detected on this path, but it is conditional — it "
            "may not execute in all scenarios. Determine if the sanitizer can be bypassed."
        ),
    }
    desc = label_desc.get(label, f"Label: {label}")

    prompt_parts = [
        f"## Code Context ({language})",
        f"**Reason for analysis**: {desc}",
    ]
    if extra_context:
        prompt_parts.append(f"\n**Additional context**: {extra_context}")
    prompt_parts.append(f"\n### CPG Data-Flow Slice\n```{language}\n{slice_text}\n```")
    prompt_parts.append(
        "\nAnalyse the code above. Report ALL vulnerabilities you find "
        "using the report_hypotheses tool."
    )

    return "\n".join(prompt_parts)


# ── HypothesisGenerator ──────────────────────────────────────────────────────


class HypothesisGenerator:
    """Generate vulnerability hypotheses from CPG-annotated paths.

    Usage::

        gen = HypothesisGenerator(query, router, provider, language)
        hypotheses = await gen.generate(annotated_paths)
    """

    def __init__(
        self,
        query: CPGQuery,
        router: ModelRouter,
        cheap_provider: AnthropicProvider,
        mid_provider: AnthropicProvider,
        strong_provider: AnthropicProvider,
        language: str,
        nudge_loop: NudgeLoop | None = None,
    ) -> None:
        self._query = query
        self._router = router
        self._language = language
        self._providers = {
            "anthropic": mid_provider,  # mid == strong share provider
            "deepseek": cheap_provider,
        }
        # Override strong to use same provider as mid (just different model)
        self._cheap = cheap_provider
        self._mid = mid_provider
        self._strong = strong_provider
        self._nudge_loop = nudge_loop

    # ── Public API ──────────────────────────────────────────────────────

    async def generate(
        self,
        annotated_paths: list[Any],  # AnnotatedPath
    ) -> list[Hypothesis]:
        """Generate hypotheses for a batch of annotated paths.

        Only processes labels that need LLM analysis:
        HEURISTIC_SINK, EXPOSED_NO_SOURCE, UNCOVERED_SINK.
        """
        hypotheses: list[Hypothesis] = []

        for ap in annotated_paths:
            label = getattr(ap, "label", None)
            if label is None:
                continue

            label_str = label.value if hasattr(label, "value") else str(label)

            if label_str in (
                "confirmed_taint",
                "sanitized_taint",
                "missing_auth",
                "config_issue",
                "unreachable_sink",
                "trust_boundary_crossing",
            ):
                # These either don't need LLM or are handled by Validator
                continue

            generated = await self._generate_one(ap, label_str)
            hypotheses.extend(generated)

        logger.info(
            "hypothesis_generation_complete",
            total_hypotheses=len(hypotheses),
            input_paths=len(annotated_paths),
        )
        return hypotheses

    async def blind_scan(
        self,
        blind_spots: list[BlindSpot],
        file_snippets: dict[str, str],
    ) -> list[Hypothesis]:
        """Generate hypotheses for coverage blind spots.

        Each blind spot is paired with relevant file snippets for context.
        """
        if not blind_spots:
            return []

        # Build prompt from blind spots
        bs_text = "\n".join(
            f"- [{bs.severity}] {bs.location}: {bs.reason}\n  Recommendation: {bs.recommendation}"
            for bs in blind_spots[:20]  # limit prompt size
        )

        snippets_text = ""
        for fname, code in list(file_snippets.items())[:5]:
            snippets_text += f"\n### {fname}\n```{self._language}\n{code[:2000]}\n```\n"

        user_prompt = (
            f"## Coverage Blind Spots\n{bs_text}\n\n"
            f"## Relevant Code Files\n{snippets_text}\n\n"
            "Analyse the code for vulnerabilities matching the blind spot "
            "categories above. Use the report_hypotheses tool."
        )

        try:
            result = await self._cheap.generate_structured(
                messages=[{"role": "user", "content": user_prompt}],
                model=self._router.CHEAP_SPEC.model_id,
                output_schema=HYPOTHESIS_SCHEMA,
                system=SYSTEM_PROMPT,
                max_tokens=4096,
                temperature=0.1,
            )
            return self._parse_response(result)
        except Exception:
            logger.exception("blind_scan_failed")
            return []

    # ── Internal ────────────────────────────────────────────────────────

    async def _generate_one(
        self,
        annotated: Any,
        label_str: str,
    ) -> list[Hypothesis]:
        """Generate hypotheses for a single annotated path."""
        path = getattr(annotated, "path", None)
        if path is None:
            return []

        # 1. Build CPG slice
        slice_text = self._query.slice_path(path, context_lines=3)

        # 2. Assess complexity and route
        path_len = len(path.nodes) if path.nodes else 0
        cross_file = self._count_files(path)

        complexity = self._router.assess_complexity(
            path_length=path_len,
            cross_file_count=cross_file,
        )
        task = Task(
            task_type=TaskType.HYPOTHESIS_GENERATION,
            complexity=complexity,
            estimated_prompt_tokens=len(slice_text) // 3,
            metadata={"label": label_str},
        )
        provider, model_id = self._router.route(task)

        # 3. Build prompt
        extra = ""
        metadata = getattr(annotated, "metadata", {}) or {}
        if label_str == "heuristic_sink":
            score = metadata.get("score", 0)
            keywords = metadata.get("keywords", [])
            extra = f"Heuristic score: {score}/100. Matched keywords: {', '.join(keywords)}"
        elif label_str == "exposed_no_source":
            ep = metadata.get("endpoint", "")
            extra = f"Endpoint: {ep}"

        user_prompt = _code_slice_prompt(
            slice_text,
            self._language,
            label_str,
            extra,
        )

        # 4. Call LLM (with nudge protection if configured)
        try:
            if self._nudge_loop is not None:
                from hyqagent.scanner.nudge import stop_on_empty, stop_on_low_confidence

                nudge_result = await self._nudge_loop.run(
                    provider=provider,
                    model=model_id,
                    messages=[{"role": "user", "content": user_prompt}],
                    output_schema=HYPOTHESIS_SCHEMA,
                    system=SYSTEM_PROMPT,
                    max_tokens=4096,
                    temperature=0.1,
                    stop_hooks=[stop_on_empty("hypotheses"), stop_on_low_confidence(0.3)],
                )
                if nudge_result.success:
                    return self._parse_response(nudge_result.data)
                logger.warning(
                    "nudge_loop_incomplete",
                    label=label_str,
                    reason=nudge_result.termination_reason,
                    turns=nudge_result.turns,
                )
                return []
            else:
                result = await provider.generate_structured(
                    messages=[{"role": "user", "content": user_prompt}],
                    model=model_id,
                    output_schema=HYPOTHESIS_SCHEMA,
                    system=SYSTEM_PROMPT,
                    max_tokens=4096,
                    temperature=0.1,
                )
                return self._parse_response(result)
        except Exception:
            logger.exception(
                "hypothesis_generation_failed",
                label=label_str,
                model=model_id,
            )
            return []

    def _parse_response(self, raw: dict[str, Any]) -> list[Hypothesis]:
        """Parse structured LLM response into Hypothesis objects."""
        items = raw.get("hypotheses", [])
        if not isinstance(items, list):
            return []

        hypotheses: list[Hypothesis] = []
        for item in items:
            if not isinstance(item, dict):
                continue
            hypotheses.append(
                Hypothesis(
                    id=f"hyp-{uuid.uuid4().hex[:8]}",
                    vuln_type=item.get("vuln_type", "unknown"),
                    cwe_id=item.get("cwe_id", ""),
                    severity=item.get("severity", "medium"),
                    confidence=float(item.get("confidence", 0.5)),
                    title=item.get("title", "Untitled"),
                    description=item.get("description", ""),
                    source_location=item.get("source_location", ""),
                    sink_location=item.get("sink_location", ""),
                    evidence="",
                    reasoning=item.get("reasoning", ""),
                    remediation=item.get("remediation", ""),
                )
            )
        return hypotheses

    @staticmethod
    def _count_files(path: GraphPath) -> int:
        """Count unique files across path nodes."""
        files: set[str] = set()
        for node in path.nodes:
            loc = getattr(node, "location", "")
            if ":" in loc:
                files.add(loc.rsplit(":", 1)[0])
        return len(files)
